export const DASHBOARD_CONFIG = Object.freeze({
  apiUrl: "https://api-v3.raydium.io/pools/info/list-v2?size=1000&hasReward=false&sortField=liquidity&sortType=desc&mintFilter=RWA",
  usdcMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
  priceScaleOverrides: Object.freeze({
    XsEH7wWfJJu2ZT3UCFeVfALnVA6CP5ur7Ee11KmzVpL: 0.1,
  }),
  capital: 1_000,
  tvlEnterThreshold: 5_000,
  tvlExitHysteresis: 4_000,
  autoExecution: false,
  execution: Object.freeze({
    solPriceUsd: Number.isFinite(Number(process.env.SOL_PRICE_USD)) ? Number(process.env.SOL_PRICE_USD) : null,
    baseFeeLamportsPerSignature: Number.isFinite(Number(process.env.SOLANA_BASE_FEE_LAMPORTS)) ? Number(process.env.SOLANA_BASE_FEE_LAMPORTS) : 5_000,
    estimatedSignaturesByAction: Object.freeze({ OPEN: 3, MOVE_CORE: 3, MOVE_BOTH: 5, CLOSE: 2 }),
  }),
  rpcUrls: Object.freeze([
    ...(process.env.SOLANA_RPC_URLS?.split(",").map((value) => value.trim()).filter(Boolean) ?? []),
    ...(process.env.SOLANA_RPC_URL?.trim() ? [process.env.SOLANA_RPC_URL.trim()] : []),
    "https://api.mainnet.solana.com",
  ]),
  evidence: Object.freeze({
    cacheDir: process.env.RWA_EVIDENCE_DIR?.trim() || ".cache/rwa-evidence",
    freshnessSlaMs: 30 * 60_000,
    signaturePageLimit: Number(process.env.RWA_SIGNATURE_PAGE_LIMIT) || 300,
    maxSignaturePagesPerPool: Number(process.env.RWA_MAX_SIGNATURE_PAGES_PER_POOL) || 12,
    maxTransactionsPerPool: Number(process.env.RWA_MAX_TRANSACTIONS_PER_POOL) || 3_600,
    maxPoolsPerBuild: 5,
    replayCoverageThreshold: Number.isFinite(Number(process.env.RWA_REPLAY_COVERAGE_THRESHOLD)) ? Number(process.env.RWA_REPLAY_COVERAGE_THRESHOLD) : 1,
    pathCoverageThreshold: Number.isFinite(Number(process.env.RWA_PATH_COVERAGE_THRESHOLD)) ? Number(process.env.RWA_PATH_COVERAGE_THRESHOLD) : 0.99,
    feeCoverageThreshold: Number.isFinite(Number(process.env.RWA_FEE_COVERAGE_THRESHOLD)) ? Number(process.env.RWA_FEE_COVERAGE_THRESHOLD) : 0.99,
    rpcMaxConcurrency: 6,
    rpcGlobalRps: 6,
    rpcTransactionRps: 3,
    rpcSignaturesRps: 1,
  }),
  coreWidths: Object.freeze([0.0025, 0.005, 0.0075, 0.01, 0.015, 0.02]),
  bufferWidths: Object.freeze([0.02, 0.03, 0.05, 0.075, 0.1]),
  allocations: Object.freeze([
    Object.freeze({ core: 0.8, buffer: 0.2 }),
    Object.freeze({ core: 0.7, buffer: 0.3 }),
    Object.freeze({ core: 0.6, buffer: 0.4 }),
  ]),
  opportunityFreshnessSlaMs: 30 * 60_000,
  verificationFreshnessSlaMs: 6 * 60 * 60_000,
  refreshIntervalMs: 60_000,
});
