export function renderRuntime(config) {
  return `const CONFIG=${JSON.stringify({
    snapshotUrl: "./top3.json",
    refreshIntervalMs: config.refreshIntervalMs,
  })};
const ACTIONS=new Set(['OPEN_READY','WATCH','REVIEW','BLOCKED']);
const VERIFICATION_STATUSES=new Set(['READY','NEAR_READY','BLOCKED']);
const OPPORTUNITY_STATUSES=new Set(['READY','WATCH','BLOCKED']);
const esc=(value)=>String(value??'').replace(/[&<>"']/g,(char)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const knownNumber=(value)=>value!==null&&value!==undefined&&Number.isFinite(Number(value));
const fmt=(value,digits=2)=>knownNumber(value)?Number(value).toLocaleString('en-US',{minimumFractionDigits:digits,maximumFractionDigits:digits}):'UNAVAILABLE';
const usd=(value,digits=2)=>knownNumber(value)?'$'+fmt(value,digits):'UNAVAILABLE';
const range=(lower,upper)=>knownNumber(lower)&&knownNumber(upper)?fmt(lower,4)+' – '+fmt(upper,4):'UNAVAILABLE';
const actionClass=(value)=>String(value??'BLOCKED').toLowerCase().replaceAll('_','-');
const verificationClass=(status)=>status==='READY'?'status-ready':status==='NEAR_READY'?'status-near':'status-blocked';
const opportunityClass=(status)=>status==='READY'?'status-ready':status==='WATCH'?'status-near':'status-blocked';
const verificationText=(status)=>VERIFICATION_STATUSES.has(status)?status:'BLOCKED';
const opportunityText=(status)=>OPPORTUNITY_STATUSES.has(status)?status:'BLOCKED';
const rowValues=(row)=>({pair:row.pair,opportunityScore:row.opportunityScore,netEstimate:row.netEstimate,coreCapital:row.coreCapital,coreLower:row.coreLower,coreUpper:row.coreUpper,bufferCapital:row.bufferCapital,bufferLower:row.bufferLower,bufferUpper:row.bufferUpper,confidence:row.confidence,action:ACTIONS.has(row.action)?row.action:'BLOCKED'});
const renderRow=(row)=>{const value=rowValues(row);return '<article class="optimizer-row" data-pool-address="'+esc(row.poolAddress)+'" role="row"><div class="row-grid"><div class="pair" role="cell"><strong>'+esc(value.pair)+'</strong></div><div class="score" role="cell"><strong>'+esc(fmt(value.opportunityScore,1))+'</strong></div><div class="net" role="cell"><strong>'+esc(usd(value.netEstimate,2))+'</strong></div><div class="strategy" role="cell"><strong>'+esc(usd(value.coreCapital,0))+'</strong><em>'+esc(range(value.coreLower,value.coreUpper))+'</em></div><div class="strategy" role="cell"><strong>'+esc(usd(value.bufferCapital,0))+'</strong><em>'+esc(range(value.bufferLower,value.bufferUpper))+'</em></div><div class="confidence" role="cell"><strong>'+esc(fmt(value.confidence,1))+'%</strong></div><div class="action '+actionClass(value.action)+'" role="cell"><strong>'+esc(value.action)+'</strong></div></div><div class="row-tools"><button class="why-trigger" type="button" data-pool-address="'+esc(row.poolAddress)+'">WHY</button></div></article>'};
const validNumber=(value)=>value===null||Number.isFinite(Number(value));
const validRow=(row)=>row&&typeof row==='object'&&typeof row.pair==='string'&&OPPORTUNITY_STATUSES.has(row.opportunityStatus)&&ACTIONS.has(row.action)&&Number.isFinite(Number(row.opportunityScore))&&Number.isFinite(Number(row.confidence))&&validNumber(row.netEstimate)&&[row.coreCapital,row.coreLower,row.coreUpper,row.bufferCapital,row.bufferLower,row.bufferUpper].every(validNumber)&&Array.isArray(row.evidence);
const validDiagnostic=(row)=>row&&typeof row==='object'&&typeof row.poolAddress==='string'&&typeof row.pair==='string'&&VERIFICATION_STATUSES.has(row.status)&&Array.isArray(row.evidence);
const validSnapshot=(snapshot)=>Boolean(snapshot&&snapshot.schemaVersion===1&&typeof snapshot.generatedAt==='string'&&typeof snapshot.snapshotHash==='string'&&/^[a-f0-9]{64}$/.test(snapshot.snapshotHash)&&snapshot.dataFreshness&&snapshot.scope?.capital===1000&&snapshot.scope?.autoExecution===false&&Array.isArray(snapshot.top3)&&snapshot.top3.every(validRow)&&snapshot.diagnostics&&snapshot.diagnostics.version===1&&Array.isArray(snapshot.diagnostics.matrix)&&snapshot.diagnostics.matrix.every(validDiagnostic));
const freshSnapshot=(snapshot)=>{const timestamp=Date.parse(snapshot.generatedAt);const sla=Number(snapshot.dataFreshness?.slaMs);return Number.isFinite(timestamp)&&Number.isFinite(sla)&&Date.now()-timestamp<=sla&&snapshot.dataFreshness?.state==='FRESH'};
const diagnosticMap=(snapshot)=>new Map((snapshot.diagnostics?.matrix??[]).map((row)=>[row.poolAddress,row]));
const setStatus=(text,state)=>{const target=document.querySelector('#live-status');if(target){target.textContent=text;target.dataset.state=state}};
const setTimestamp=(value)=>{const date=new Date(value);const target=document.querySelector('#observed-at');const wrap=document.querySelector('#observed-wrap');if(!target||!wrap||!Number.isFinite(date.valueOf()))return;target.textContent=new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(date).replaceAll('/','-');wrap.hidden=false};
const setCount=(snapshot)=>{const target=document.querySelector('#market-count');if(target)target.textContent='CANDIDATES '+Math.min(3,Array.isArray(snapshot.top3)?snapshot.top3.length:0)+' / 3'};
const renderEmpty=(reason)=>{const list=document.querySelector('#ranking-list');const empty=document.querySelector('#empty-state');if(list)list.replaceChildren();if(empty){empty.innerHTML='<strong>等待机会快照</strong><span class="reason">'+esc(reason??'当前没有可展示的 RWA/USDC 机会候选。')+'</span>';empty.hidden=false}};
const renderVerification=(snapshot)=>{const list=document.querySelector('#verification-list');if(!list)return;const rows=(snapshot.diagnostics?.nearest??[]).slice(0,8);list.innerHTML=rows.length?rows.map((row)=>'<div class="verification-row"><span class="pair-label">'+esc(row.pair)+'</span><strong class="'+verificationClass(row.status)+'">'+esc(verificationText(row.status))+'</strong><span class="blocker">'+esc(row.primaryBlocker?.display??row.primaryBlocker?.label??'证据已通过')+'</span><button class="why-trigger verification-why" type="button" data-pool-address="'+esc(row.poolAddress)+'">WHY</button></div>').join(''):'<div class="verification-row"><span class="pair-label">等待诊断快照</span><span class="blocker">等待证据</span></div>'};
const renderNetRange=(rangeValue)=>{if(!rangeValue)return '';return '<section class="net-range"><h3>NET LOW / BASE / HIGH</h3><div class="net-range-grid"><div><small>NET LOW</small><strong>'+esc(usd(rangeValue.NET_LOW,2))+'</strong></div><div><small>NET BASE</small><strong>'+esc(usd(rangeValue.NET_BASE,2))+'</strong></div><div><small>NET HIGH</small><strong>'+esc(usd(rangeValue.NET_HIGH,2))+'</strong></div></div><small>'+esc(rangeValue.reason??'')+'</small></section>'};
const renderOpportunity=(diagnostic)=>{const opportunity=diagnostic.opportunity;if(!opportunity)return '';const score=diagnostic.opportunityScore===null?'UNAVAILABLE':fmt(diagnostic.opportunityScore,1);const status=opportunityText(diagnostic.opportunityStatus);return '<section class="opportunity-evidence"><h3>OPPORTUNITY</h3><div><strong>'+esc(score)+'</strong><span class="'+opportunityClass(status)+'">'+esc(status)+'</span></div><small>Score 来源：24h volume · LP fee · TVL · fee tier · liquidity · price activity proxy</small></section>'};
const renderWhy=(diagnostic)=>{const drawer=document.querySelector('#why-drawer');if(!drawer||!diagnostic)return;const opportunityStatus=opportunityText(diagnostic.opportunityStatus);drawer.innerHTML='<header><div><h2>'+esc(diagnostic.pair)+'</h2><div class="drawer-status '+opportunityClass(opportunityStatus)+'">Opportunity '+esc(opportunityStatus)+'</div><small>Verification '+esc(verificationText(diagnostic.status))+'</small></div><button class="drawer-close" type="button" aria-label="关闭 WHY">×</button></header>'+renderOpportunity(diagnostic)+'<div class="evidence-list">'+(diagnostic.evidence??[]).map((entry)=>'<div class="evidence-row"><div><strong>'+esc(entry.label)+'</strong><small>'+esc(entry.reason??'')+'</small></div><span class="evidence-status '+verificationClass(entry.status==='PASS'?'READY':entry.status==='WARN'?'NEAR_READY':'BLOCKED')+'">'+esc(entry.display??entry.status)+'</span></div>').join('')+'</div>'+renderNetRange(diagnostic.netRange)+'<div class="volatility">Volatility regime：<strong>'+esc(diagnostic.volatilityRegime?.regime??'WAITING')+'</strong><br>'+esc(diagnostic.volatilityRegime?.reason??'')+'</div>';drawer.hidden=false;drawer.querySelector('.drawer-close')?.addEventListener('click',()=>{drawer.hidden=true})};
const bindWhy=(snapshot)=>{const map=diagnosticMap(snapshot);document.querySelectorAll('.why-trigger').forEach((button)=>button.addEventListener('click',()=>renderWhy(map.get(button.dataset.poolAddress))))};
const renderRows=(snapshot)=>{const rows=Array.isArray(snapshot.top3)?snapshot.top3.slice(0,3):[];const list=document.querySelector('#ranking-list');const empty=document.querySelector('#empty-state');if(!list||!empty)return;if(rows.length===0){renderEmpty();return}list.innerHTML=rows.map(renderRow).join('');empty.replaceChildren();empty.hidden=true};
let requestInFlight=false;
const refresh=async()=>{if(requestInFlight||document.hidden)return;requestInFlight=true;try{const response=await fetch(CONFIG.snapshotUrl+'?_='+Date.now(),{cache:'no-store',headers:{accept:'application/json'}});if(!response.ok)throw new Error('HTTP '+response.status);const snapshot=await response.json();if(!validSnapshot(snapshot))throw new Error('top3.json 格式无效');setCount(snapshot);setTimestamp(snapshot.generatedAt);renderVerification(snapshot);const main=document.querySelector('main');if(main)main.dataset.snapshotHash=snapshot.snapshotHash;if(!freshSnapshot(snapshot)){setStatus('机会快照已过期 · 当前不显示候选','warning');renderEmpty('当前快照已过期，等待新的 top3.json。');bindWhy(snapshot);return}renderRows(snapshot);bindWhy(snapshot);if(snapshot.top3.length===0)setStatus('等待机会快照 · 当前没有候选','warning');else setStatus('已载入 '+Math.min(3,snapshot.top3.length)+' 个机会候选','fresh')}catch(error){setStatus('top3.json 读取失败 · 当前不显示候选','warning');renderEmpty('无法读取 mobile-dashboard/top3.json。');const target=document.querySelector('#live-status');if(target)target.title=error instanceof Error?error.message:'读取失败'}finally{requestInFlight=false}};
document.addEventListener('visibilitychange',()=>{if(!document.hidden)void refresh()});
void refresh();window.setInterval(refresh,CONFIG.refreshIntervalMs);`;
}
