export function renderRuntime(config) {
  return `const CONFIG=${JSON.stringify({
  snapshotUrl: "./top3.json",
  refreshIntervalMs: config.refreshIntervalMs,
})};
const ACTIONS=new Set(['OPEN_READY','WATCH','REVIEW','BLOCKED']);
const VERIFICATION_STATUSES=new Set(['READY','NEAR_READY','BLOCKED']);
const OPPORTUNITY_STATUSES=new Set(['READY','WATCH','BLOCKED']);
const DEXES=new Set(['Raydium','Meteora']);
const esc=(value)=>String(value??'').replace(/[&<>"']/g,(char)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const knownNumber=(value)=>value!==null&&value!==undefined&&Number.isFinite(Number(value));
const validNumber=(value)=>value===null||knownNumber(value);
const fmt=(value,digits=2)=>knownNumber(value)?Number(value).toLocaleString('en-US',{minimumFractionDigits:digits,maximumFractionDigits:digits}):'等待数据';
const usd=(value,digits=2)=>knownNumber(value)?'$'+fmt(value,digits):'等待数据';
const feeTier=(value)=>knownNumber(value)?fmt(Number(value)*100,2)+'%':'等待数据';
const pairLabel=(value)=>String(value??'').replace('/',' / ');
const shortAddress=(value)=>{const address=String(value??'');return address.length>14?address.slice(0,6)+'…'+address.slice(-6):address||'等待数据'};
const actionLabel=(value)=>value==='OPEN_READY'?'可考虑':value==='BLOCKED'?'暂停':'观察';
const actionClass=(value)=>String(value??'BLOCKED').toLowerCase().replaceAll('_','-');
const verificationClass=(status)=>status==='READY'?'status-ready':status==='NEAR_READY'?'status-near':'status-blocked';
const opportunityClass=(status)=>status==='READY'?'status-ready':status==='WATCH'?'status-near':'status-blocked';
const verificationText=(status)=>VERIFICATION_STATUSES.has(status)?status:'BLOCKED';
const opportunityText=(status)=>OPPORTUNITY_STATUSES.has(status)?status:'BLOCKED';
const rowValues=(row)=>({rank:row.rank,pair:pairLabel(row.pair),tvl:row.tvl,volume24h:row.volume24h,lpFee24h:row.lpFee24h,feeTier:row.feeTier,action:ACTIONS.has(row.action)?row.action:'BLOCKED'});
const renderRow=(row)=>{const value=rowValues(row);return '<article class="optimizer-row" data-pool-address="'+esc(row.poolAddress)+'" role="row"><div class="row-grid"><div class="rank" role="cell"><strong>'+esc(String(value.rank??'').padStart(2,'0'))+'</strong></div><div class="pool" role="cell"><strong>'+esc(value.pair)+'</strong><small>Fee Tier '+esc(feeTier(value.feeTier))+'</small></div><div class="volume" role="cell"><strong>'+esc(usd(value.volume24h,0))+'</strong></div><div class="lp-fee" role="cell"><strong>'+esc(usd(value.lpFee24h,2))+'</strong></div><div class="tvl" role="cell"><strong>'+esc(usd(value.tvl,0))+'</strong></div><div class="fee" role="cell"><strong>'+esc(feeTier(value.feeTier))+'</strong></div><div class="action '+actionClass(value.action)+'" role="cell"><strong>'+esc(actionLabel(value.action))+'</strong></div></div><div class="row-tools"><button class="details-trigger" type="button" data-pool-address="'+esc(row.poolAddress)+'">详情</button></div></article>'};
const validRow=(row)=>row&&typeof row==='object'&&typeof row.pair==='string'&&OPPORTUNITY_STATUSES.has(row.opportunityStatus)&&ACTIONS.has(row.action)&&Number.isFinite(Number(row.opportunityScore))&&Number.isFinite(Number(row.confidence))&&[row.tvl,row.volume24h,row.lpFee24h,row.feeTier,row.netEstimate,row.coreCapital,row.coreLower,row.coreUpper,row.bufferCapital,row.bufferLower,row.bufferUpper].every(validNumber)&&Array.isArray(row.evidence);
const validFeeRow=(row,index)=>row&&typeof row==='object'&&row.rank===index+1&&DEXES.has(row.dex)&&typeof row.pair==='string'&&typeof row.poolAddress==='string'&&[row.tvl,row.volume24h,row.lpFee24h,row.feeTier].every(validNumber);
const validDiagnostic=(row)=>row&&typeof row==='object'&&typeof row.poolAddress==='string'&&typeof row.pair==='string'&&VERIFICATION_STATUSES.has(row.status)&&Array.isArray(row.evidence);
const validSnapshot=(snapshot)=>Boolean(snapshot&&snapshot.schemaVersion===1&&typeof snapshot.generatedAt==='string'&&typeof snapshot.opportunityGeneratedAt==='string'&&typeof snapshot.snapshotHash==='string'&&/^[a-f0-9]{64}$/.test(snapshot.snapshotHash)&&snapshot.opportunityFreshness&&snapshot.scope?.capital===1000&&snapshot.scope?.autoExecution===false&&Array.isArray(snapshot.candidates)&&snapshot.candidates.every(validRow)&&Array.isArray(snapshot.marketHeat)&&snapshot.marketHeat.every((row,index)=>row&&row.rank===index+1)&&snapshot.feeLeaderboards&&Array.isArray(snapshot.feeLeaderboards.overall)&&snapshot.feeLeaderboards.overall.every(validFeeRow)&&Array.isArray(snapshot.feeLeaderboards.rwa)&&snapshot.feeLeaderboards.rwa.every(validFeeRow)&&(!snapshot.diagnostics||snapshot.diagnostics.version===1&&Array.isArray(snapshot.diagnostics.matrix)&&snapshot.diagnostics.matrix.every(validDiagnostic)));
const candidateRows=(snapshot)=>{const seen=new Set();return (Array.isArray(snapshot.candidates)?snapshot.candidates:[]).filter((row)=>{const tier=knownNumber(row.feeTier)?Number(row.feeTier):'unknown';const key=String(row.pair)+'::'+tier;if(seen.has(key))return false;seen.add(key);return true}).slice(0,3)};
const feeRows=(snapshot,key)=>Array.isArray(snapshot.feeLeaderboards?.[key])?snapshot.feeLeaderboards[key]:[];
const freshSnapshot=(snapshot)=>{const timestamp=Date.parse(snapshot.opportunityGeneratedAt);const sla=Number(snapshot.opportunityFreshness?.slaMs);return Number.isFinite(timestamp)&&Number.isFinite(sla)&&Date.now()-timestamp<=sla&&snapshot.opportunityFreshness?.state==='FRESH'};
const diagnosticMap=(snapshot)=>new Map((snapshot.diagnostics?.matrix??[]).map((row)=>[row.poolAddress,row]));
const setStatus=(text,state)=>{const target=document.querySelector('#live-status');if(target){target.textContent=text;target.dataset.state=state}};
const setTimestamp=(value)=>{const date=new Date(value);const target=document.querySelector('#observed-at');const wrap=document.querySelector('#observed-wrap');if(!target||!wrap||!Number.isFinite(date.valueOf()))return;target.textContent=new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(date).replaceAll('/','-');wrap.hidden=false};
const renderEmpty=(reason)=>{const list=document.querySelector('#ranking-list');const empty=document.querySelector('#empty-state');if(list)list.replaceChildren();if(empty){empty.innerHTML='<strong>等待计算</strong><span class="reason">'+esc(reason??'当前没有可展示的 RWA / USDC 机会。')+'</span>';empty.hidden=false}};
const renderVerification=(snapshot)=>{const list=document.querySelector('#verification-list');if(!list)return;const rows=(snapshot.diagnostics?.nearest??[]).slice(0,8);list.innerHTML=rows.length?rows.map((row)=>'<div class="verification-row"><span class="pair-label">'+esc(pairLabel(row.pair))+'</span><strong class="'+verificationClass(row.status)+'">'+esc(verificationText(row.status))+'</strong><span class="blocker">'+esc(row.primaryBlocker?.display??row.primaryBlocker?.label??'证据已通过')+'</span><button class="details-trigger verification-details" type="button" data-pool-address="'+esc(row.poolAddress)+'">详情</button></div>').join(''):'<div class="verification-row"><span class="pair-label">等待计算</span><span class="blocker">证据快照更新中</span></div>'};
const renderOpportunity=(diagnostic)=>{const opportunity=diagnostic.opportunity;if(!opportunity)return '';const score=knownNumber(diagnostic.opportunityScore)?fmt(diagnostic.opportunityScore,1):'等待数据';const confidence=knownNumber(diagnostic.opportunityConfidence)?fmt(diagnostic.opportunityConfidence,1)+'%':'等待数据';const status=opportunityText(diagnostic.opportunityStatus);return '<section class="opportunity-evidence"><h3>Opportunity Score</h3><div><strong>'+esc(score)+'</strong><span class="'+opportunityClass(status)+'">'+esc(status)+'</span></div><small>Confidence '+esc(confidence)+' · 来源：24h 成交、LP Fee、TVL、费率、流动性与价格活跃度</small></section>'};
const renderWhy=(diagnostic)=>{const drawer=document.querySelector('#why-drawer');if(!drawer||!diagnostic)return;const opportunityStatus=opportunityText(diagnostic.opportunityStatus);const confidence=knownNumber(diagnostic.opportunityConfidence)?fmt(diagnostic.opportunityConfidence,1)+'%':'等待数据';drawer.innerHTML='<header><div><h2>'+esc(pairLabel(diagnostic.pair))+'</h2><div class="drawer-status '+opportunityClass(opportunityStatus)+'">机会层 '+esc(opportunityStatus)+'</div><div class="drawer-meta">Confidence '+esc(confidence)+' · Verification '+esc(verificationText(diagnostic.status))+'</div></div><button class="drawer-close" type="button" aria-label="关闭详情">×</button></header>'+renderOpportunity(diagnostic)+'<div class="evidence-list"><h3>Evidence</h3>'+(diagnostic.evidence??[]).map((entry)=>'<div class="evidence-row"><div><strong>'+esc(entry.label)+'</strong><small>'+esc(entry.reason??'')+'</small></div><span class="evidence-status '+verificationClass(entry.status==='PASS'?'READY':entry.status==='WARN'?'NEAR_READY':'BLOCKED')+'">'+esc(entry.display??entry.status)+'</span></div>').join('')+'</div>'+'<div class="volatility">Volatility regime：<strong>'+esc(diagnostic.volatilityRegime?.regime??'WAITING')+'</strong><br>'+esc(diagnostic.volatilityRegime?.reason??'')+'</div>';drawer.hidden=false;drawer.querySelector('.drawer-close')?.addEventListener('click',()=>{drawer.hidden=true})};
const bindDetails=(snapshot)=>{const map=diagnosticMap(snapshot);document.querySelectorAll('.details-trigger').forEach((button)=>button.addEventListener('click',()=>renderWhy(map.get(button.dataset.poolAddress))))};
const renderRows=(snapshot)=>{const rows=candidateRows(snapshot);const list=document.querySelector('#ranking-list');const empty=document.querySelector('#empty-state');if(!list||!empty)return;if(rows.length===0){renderEmpty();return}list.innerHTML=rows.map(renderRow).join('');empty.replaceChildren();empty.hidden=true};
const renderFeeRow=(row)=>'<article class="fee-row" data-pool-address="'+esc(row.poolAddress)+'" role="row"><div class="fee-grid"><div class="rank" role="cell"><strong>'+esc(String(row.rank).padStart(2,'0'))+'</strong></div><div class="pool" role="cell"><strong>'+esc(pairLabel(row.pair))+'</strong><small>'+esc(row.dex)+' · '+esc(row.poolType??'Pool')+'</small></div><div class="address" role="cell"><small title="'+esc(row.poolAddress)+'">'+esc(shortAddress(row.poolAddress))+'</small></div><div class="tvl" role="cell"><strong>'+esc(usd(row.tvl,0))+'</strong></div><div class="volume" role="cell"><strong>'+esc(usd(row.volume24h,0))+'</strong></div><div class="lp-fee" role="cell"><strong>'+esc(usd(row.lpFee24h,2))+'</strong></div><div class="fee-tier" role="cell"><strong>'+esc(feeTier(row.feeTier))+'</strong><small>'+esc(row.feeMode??'')+'</small></div><div class="copy" role="cell"><button class="copy-pool" type="button" data-pool-address="'+esc(row.poolAddress)+'">复制 Pool</button></div></div></article>';
const total=(rows,key)=>{const values=rows.map((row)=>Number(row[key])).filter(Number.isFinite);return values.length?values.reduce((sum,value)=>sum+value,0):null};
const renderFeeSummary=(rows,id)=>{const target=document.querySelector('#'+id);if(!target)return;target.innerHTML='<div><small>Top 10 总 TVL</small><strong>'+esc(usd(total(rows,'tvl'),0))+'</strong></div><div><small>Top 10 总成交量</small><strong>'+esc(usd(total(rows,'volume24h'),0))+'</strong></div><div><small>Top 10 总 Fee</small><strong>'+esc(usd(total(rows,'lpFee24h'),2))+'</strong></div>'};
const renderFeeBoard=(snapshot,key,prefix)=>{const rows=feeRows(snapshot,key);const list=document.querySelector('#'+prefix+'-list');const empty=document.querySelector('#'+prefix+'-empty');if(!list||!empty)return;if(rows.length===0){list.replaceChildren();empty.innerHTML='<strong>等待官方数据</strong><span class="reason">当前榜单没有完整的 24H Fee 证据。</span>';empty.hidden=false;return}list.innerHTML=rows.map(renderFeeRow).join('');empty.replaceChildren();empty.hidden=true;renderFeeSummary(rows,prefix+'-summary')};
const copyText=async(value)=>{if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(value);return}const area=document.createElement('textarea');area.value=value;area.style.position='fixed';area.style.opacity='0';document.body.append(area);area.select();const copied=document.execCommand('copy');area.remove();if(!copied)throw new Error('clipboard unavailable')};
const bindCopyButtons=()=>{document.querySelectorAll('.copy-pool').forEach((button)=>button.addEventListener('click',async()=>{const original=button.textContent;try{await copyText(button.dataset.poolAddress??'');button.textContent='已复制';button.dataset.state='copied';window.setTimeout(()=>{button.textContent=original;button.dataset.state=''},1200)}catch{button.textContent='复制失败';window.setTimeout(()=>{button.textContent=original},1200)}}))};
const tabConfig={fee:['tab-fee','fee-view'],rwaFee:['tab-rwa-fee','rwa-fee-view'],opportunity:['tab-opportunity','opportunity-view']};
const setTab=(key)=>{for(const [name,[buttonId,panelId]] of Object.entries(tabConfig)){const selected=name===key;const button=document.querySelector('#'+buttonId);const panel=document.querySelector('#'+panelId);if(button){button.classList.toggle('active',selected);button.setAttribute('aria-selected',String(selected))}if(panel)panel.hidden=!selected}};
const bindTabs=()=>{for(const [name,[buttonId]] of Object.entries(tabConfig))document.querySelector('#'+buttonId)?.addEventListener('click',()=>setTab(name))};
let requestInFlight=false;
const refresh=async()=>{if(requestInFlight||document.hidden)return;requestInFlight=true;try{const response=await fetch(CONFIG.snapshotUrl+'?_='+Date.now(),{cache:'no-store',headers:{accept:'application/json'}});if(!response.ok)throw new Error('HTTP '+response.status);const snapshot=await response.json();if(!validSnapshot(snapshot))throw new Error('top3.json 格式无效');setTimestamp(snapshot.feeLeaderboards?.generatedAt??snapshot.generatedAt);renderFeeBoard(snapshot,'overall','fee-view');renderFeeBoard(snapshot,'rwa','rwa-fee-view');renderVerification(snapshot);bindCopyButtons();const main=document.querySelector('main');if(main)main.dataset.snapshotHash=snapshot.snapshotHash;if(!freshSnapshot(snapshot)){setStatus('官方 Fee 已更新 · 推荐机会正在校准','fresh');renderEmpty('推荐机会快照正在更新，请稍后查看。');bindDetails(snapshot);return}renderRows(snapshot);bindDetails(snapshot);if(candidateRows(snapshot).length===0)setStatus('官方 Fee 已更新 · 暂无推荐机会','fresh');else setStatus('官方 Fee 已更新 · '+candidateRows(snapshot).length+' 个推荐池','fresh')}catch(error){setStatus('等待官方数据 · 数据读取失败','warning');renderEmpty('无法读取当前官方 Fee 数据。');const target=document.querySelector('#live-status');if(target)target.title=error instanceof Error?error.message:'读取失败'}finally{requestInFlight=false}};
bindTabs();setTab('fee');
document.addEventListener('visibilitychange',()=>{if(!document.hidden)void refresh()});
void refresh();window.setInterval(refresh,CONFIG.refreshIntervalMs);`;
}
