export function renderRuntime(config) {
  return `const CONFIG=${JSON.stringify({
    snapshotUrl: "./top3.json",
    refreshIntervalMs: config.refreshIntervalMs,
    capital: config.capital,
  })};
const ACTIONS=new Set(['OPEN_READY','WATCH','REVIEW','BLOCKED']);
const VERIFICATION_STATUSES=new Set(['READY','NEAR_READY','BLOCKED']);
const OPPORTUNITY_STATUSES=new Set(['READY','WATCH','BLOCKED']);
const esc=(value)=>String(value??'').replace(/[&<>"']/g,(char)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const knownNumber=(value)=>value!==null&&value!==undefined&&Number.isFinite(Number(value));
const validNumber=(value)=>value===null||knownNumber(value);
const fmt=(value,digits=2)=>knownNumber(value)?Number(value).toLocaleString('en-US',{minimumFractionDigits:digits,maximumFractionDigits:digits}):'等待计算';
const usd=(value,digits=2)=>knownNumber(value)?'$'+fmt(value,digits):'等待计算';
const dailyNet=(value)=>knownNumber(value)?(Number(value)>=0?'+':'−')+usd(Math.abs(Number(value)),2)+'/天':'等待计算';
const grossFee=(row)=>knownNumber(row.grossFeeEstimate)?Number(row.grossFeeEstimate):knownNumber(row.lpFee24h)&&knownNumber(row.tvl)&&Number(row.tvl)>=0?Number(row.lpFee24h)*CONFIG.capital/(Number(row.tvl)+CONFIG.capital):null;
const grossLabel=(row)=>knownNumber(grossFee(row))?usd(grossFee(row),2)+'/天':'等待计算';
const range=(lower,upper)=>knownNumber(lower)&&knownNumber(upper)?fmt(lower,4)+' – '+fmt(upper,4):'等待计算';
const feeTier=(value)=>knownNumber(value)?fmt(Number(value)*100,2)+'%':'等待计算';
const pairLabel=(value)=>String(value??'').replace('/',' / ');
const actionLabel=(value)=>value==='OPEN_READY'?'可考虑':value==='BLOCKED'?'暂停':'观察';
const actionClass=(value)=>String(value??'BLOCKED').toLowerCase().replaceAll('_','-');
const verificationClass=(status)=>status==='READY'?'status-ready':status==='NEAR_READY'?'status-near':'status-blocked';
const opportunityClass=(status)=>status==='READY'?'status-ready':status==='WATCH'?'status-near':'status-blocked';
const verificationText=(status)=>VERIFICATION_STATUSES.has(status)?status:'BLOCKED';
const opportunityText=(status)=>OPPORTUNITY_STATUSES.has(status)?status:'BLOCKED';
const rowValues=(row)=>({rank:row.rank,pair:pairLabel(row.pair),tvl:row.tvl,volume24h:row.volume24h,lpFee24h:row.lpFee24h,feeTier:row.feeTier,grossFeeEstimate:row.grossFeeEstimate,netEstimate:row.netEstimate,coreCapital:row.coreCapital,coreLower:row.coreLower,coreUpper:row.coreUpper,bufferCapital:row.bufferCapital,bufferLower:row.bufferLower,bufferUpper:row.bufferUpper,action:ACTIONS.has(row.action)?row.action:'BLOCKED'});
const renderNet=(value)=>knownNumber(value.netEstimate)?'<strong>'+esc(dailyNet(value.netEstimate))+'</strong><small>毛收益估算：'+esc(grossLabel(value))+' · 风险已校正</small>':'<strong>估算中</strong><small>毛收益估算：'+esc(grossLabel(value))+'</small><small>净收益：等待风险校正</small>';
const renderRow=(row)=>{const value=rowValues(row);return '<article class="optimizer-row" data-pool-address="'+esc(row.poolAddress)+'" role="row"><div class="row-grid"><div class="rank" role="cell"><strong>'+esc(String(value.rank??'').padStart(2,'0'))+'</strong></div><div class="pool" role="cell"><strong>'+esc(value.pair)+'</strong><small>Fee Tier '+esc(feeTier(value.feeTier))+'</small></div><div class="volume" role="cell"><strong>'+esc(usd(value.volume24h,0))+'</strong></div><div class="lp-fee" role="cell"><strong>'+esc(usd(value.lpFee24h,2))+'</strong></div><div class="tvl" role="cell"><strong>'+esc(usd(value.tvl,0))+'</strong></div><div class="fee" role="cell"><strong>'+esc(feeTier(value.feeTier))+'</strong></div><div class="net" role="cell">'+renderNet(value)+'</div><div class="action '+actionClass(value.action)+'" role="cell"><strong>'+esc(actionLabel(value.action))+'</strong></div></div><div class="row-tools"><button class="details-trigger" type="button" data-pool-address="'+esc(row.poolAddress)+'">详情</button></div></article>'};
const validRow=(row)=>row&&typeof row==='object'&&typeof row.pair==='string'&&OPPORTUNITY_STATUSES.has(row.opportunityStatus)&&ACTIONS.has(row.action)&&Number.isFinite(Number(row.opportunityScore))&&Number.isFinite(Number(row.confidence))&&[row.tvl,row.volume24h,row.lpFee24h,row.feeTier,row.netEstimate,row.coreCapital,row.coreLower,row.coreUpper,row.bufferCapital,row.bufferLower,row.bufferUpper].every(validNumber)&&Array.isArray(row.evidence);
const validDiagnostic=(row)=>row&&typeof row==='object'&&typeof row.poolAddress==='string'&&typeof row.pair==='string'&&VERIFICATION_STATUSES.has(row.status)&&Array.isArray(row.evidence);
const validSnapshot=(snapshot)=>Boolean(snapshot&&snapshot.schemaVersion===1&&typeof snapshot.generatedAt==='string'&&typeof snapshot.opportunityGeneratedAt==='string'&&typeof snapshot.snapshotHash==='string'&&/^[a-f0-9]{64}$/.test(snapshot.snapshotHash)&&snapshot.opportunityFreshness&&snapshot.scope?.capital===1000&&snapshot.scope?.autoExecution===false&&Array.isArray(snapshot.candidates)&&snapshot.candidates.every(validRow)&&(!snapshot.diagnostics||snapshot.diagnostics.version===1&&Array.isArray(snapshot.diagnostics.matrix)&&snapshot.diagnostics.matrix.every(validDiagnostic)));
const candidateRows=(snapshot)=>{const seen=new Set();return (Array.isArray(snapshot.candidates)?snapshot.candidates:[]).filter((row)=>{const tier=knownNumber(row.feeTier)?Number(row.feeTier):'unknown';const key=String(row.pair)+'::'+tier;if(seen.has(key))return false;seen.add(key);return true}).slice(0,3)};
const freshSnapshot=(snapshot)=>{const timestamp=Date.parse(snapshot.opportunityGeneratedAt);const sla=Number(snapshot.opportunityFreshness?.slaMs);return Number.isFinite(timestamp)&&Number.isFinite(sla)&&Date.now()-timestamp<=sla&&snapshot.opportunityFreshness?.state==='FRESH'};
const diagnosticMap=(snapshot)=>new Map((snapshot.diagnostics?.matrix??[]).map((row)=>[row.poolAddress,row]));
const setStatus=(text,state)=>{const target=document.querySelector('#live-status');if(target){target.textContent=text;target.dataset.state=state}};
const setTimestamp=(value)=>{const date=new Date(value);const target=document.querySelector('#observed-at');const wrap=document.querySelector('#observed-wrap');if(!target||!wrap||!Number.isFinite(date.valueOf()))return;target.textContent=new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(date).replaceAll('/','-');wrap.hidden=false};
const renderEmpty=(reason)=>{const list=document.querySelector('#ranking-list');const empty=document.querySelector('#empty-state');if(list)list.replaceChildren();if(empty){empty.innerHTML='<strong>等待计算</strong><span class="reason">'+esc(reason??'当前没有可展示的 RWA / USDC 机会。')+'</span>';empty.hidden=false}};
const renderVerification=(snapshot)=>{const list=document.querySelector('#verification-list');if(!list)return;const rows=(snapshot.diagnostics?.nearest??[]).slice(0,8);list.innerHTML=rows.length?rows.map((row)=>'<div class="verification-row"><span class="pair-label">'+esc(pairLabel(row.pair))+'</span><strong class="'+verificationClass(row.status)+'">'+esc(verificationText(row.status))+'</strong><span class="blocker">'+esc(row.primaryBlocker?.display??row.primaryBlocker?.label??'证据已通过')+'</span><button class="details-trigger verification-details" type="button" data-pool-address="'+esc(row.poolAddress)+'">详情</button></div>').join(''):'<div class="verification-row"><span class="pair-label">等待计算</span><span class="blocker">证据快照更新中</span></div>'};
const renderNetRange=(rangeValue)=>{if(!rangeValue)return '';return '<section class="net-range"><h3>NET LOW / BASE / HIGH</h3><div class="net-range-grid"><div><small>NET LOW</small><strong>'+esc(usd(rangeValue.NET_LOW,2))+'</strong></div><div><small>NET BASE</small><strong>'+esc(usd(rangeValue.NET_BASE,2))+'</strong></div><div><small>NET HIGH</small><strong>'+esc(usd(rangeValue.NET_HIGH,2))+'</strong></div></div><small>'+esc(rangeValue.reason??'')+'</small></section>'};
const renderStrategy=(label,capital,lower,upper)=>'<section class="strategy-detail"><h3>'+label+'</h3><strong>'+esc(usd(capital,0))+'</strong><span>'+esc(range(lower,upper))+'</span></section>';
const renderOpportunity=(diagnostic)=>{const opportunity=diagnostic.opportunity;if(!opportunity)return '';const score=knownNumber(diagnostic.opportunityScore)?fmt(diagnostic.opportunityScore,1):'等待计算';const confidence=knownNumber(diagnostic.opportunityConfidence)?fmt(diagnostic.opportunityConfidence,1)+'%':'等待计算';const status=opportunityText(diagnostic.opportunityStatus);return '<section class="opportunity-evidence"><h3>Opportunity Score</h3><div><strong>'+esc(score)+'</strong><span class="'+opportunityClass(status)+'">'+esc(status)+'</span></div><small>Confidence '+esc(confidence)+' · 来源：24h 成交、LP Fee、TVL、费率、流动性与价格活跃度</small></section>'};
const renderWhy=(diagnostic,candidate)=>{const drawer=document.querySelector('#why-drawer');if(!drawer||!diagnostic)return;const opportunityStatus=opportunityText(diagnostic.opportunityStatus);const confidence=knownNumber(diagnostic.opportunityConfidence)?fmt(diagnostic.opportunityConfidence,1)+'%':'等待计算';drawer.innerHTML='<header><div><h2>'+esc(pairLabel(diagnostic.pair))+'</h2><div class="drawer-status '+opportunityClass(opportunityStatus)+'">机会层 '+esc(opportunityStatus)+'</div><div class="drawer-meta">Confidence '+esc(confidence)+' · Verification '+esc(verificationText(diagnostic.status))+'</div></div><button class="drawer-close" type="button" aria-label="关闭详情">×</button></header>'+renderOpportunity(diagnostic)+'<section class="strategy-details"><h3>Core / Buffer</h3>'+renderStrategy('Core',candidate?.coreCapital,candidate?.coreLower,candidate?.coreUpper)+renderStrategy('Buffer',candidate?.bufferCapital,candidate?.bufferLower,candidate?.bufferUpper)+'</section><div class="evidence-list"><h3>Evidence</h3>'+(diagnostic.evidence??[]).map((entry)=>'<div class="evidence-row"><div><strong>'+esc(entry.label)+'</strong><small>'+esc(entry.reason??'')+'</small></div><span class="evidence-status '+verificationClass(entry.status==='PASS'?'READY':entry.status==='WARN'?'NEAR_READY':'BLOCKED')+'">'+esc(entry.display??entry.status)+'</span></div>').join('')+'</div>'+renderNetRange(diagnostic.netRange)+'<div class="volatility">Volatility regime：<strong>'+esc(diagnostic.volatilityRegime?.regime??'WAITING')+'</strong><br>'+esc(diagnostic.volatilityRegime?.reason??'')+'</div>';drawer.hidden=false;drawer.querySelector('.drawer-close')?.addEventListener('click',()=>{drawer.hidden=true})};
const bindDetails=(snapshot)=>{const map=diagnosticMap(snapshot);const candidates=new Map(candidateRows(snapshot).map((row)=>[row.poolAddress,row]));document.querySelectorAll('.details-trigger').forEach((button)=>button.addEventListener('click',()=>renderWhy(map.get(button.dataset.poolAddress),candidates.get(button.dataset.poolAddress))))};
const renderRows=(snapshot)=>{const rows=candidateRows(snapshot);const list=document.querySelector('#ranking-list');const empty=document.querySelector('#empty-state');if(!list||!empty)return;if(rows.length===0){renderEmpty();return}list.innerHTML=rows.map(renderRow).join('');empty.replaceChildren();empty.hidden=true};
let requestInFlight=false;
const refresh=async()=>{if(requestInFlight||document.hidden)return;requestInFlight=true;try{const response=await fetch(CONFIG.snapshotUrl+'?_='+Date.now(),{cache:'no-store',headers:{accept:'application/json'}});if(!response.ok)throw new Error('HTTP '+response.status);const snapshot=await response.json();if(!validSnapshot(snapshot))throw new Error('top3.json 格式无效');setTimestamp(snapshot.opportunityGeneratedAt);renderVerification(snapshot);const main=document.querySelector('main');if(main)main.dataset.snapshotHash=snapshot.snapshotHash;if(!freshSnapshot(snapshot)){setStatus('等待计算 · 数据正在更新','warning');renderEmpty('机会数据正在更新，请稍后查看。');bindDetails(snapshot);return}renderRows(snapshot);bindDetails(snapshot);if(candidateRows(snapshot).length===0)setStatus('等待计算 · 暂无可展示的池','warning');else setStatus('数据已更新 · '+candidateRows(snapshot).length+' 个池','fresh')}catch(error){setStatus('等待计算 · 数据读取失败','warning');renderEmpty('无法读取当前 RWA / USDC 市场数据。');const target=document.querySelector('#live-status');if(target)target.title=error instanceof Error?error.message:'读取失败'}finally{requestInFlight=false}};
document.addEventListener('visibilitychange',()=>{if(!document.hidden)void refresh()});
void refresh();window.setInterval(refresh,CONFIG.refreshIntervalMs);`;
}
